name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Run a one-line script
      run: which python
    - name: Run a multi-line script
      run: |
        pip3 install pytest
        git clone https://github.com/rushabh-v/cupy.git
        cd cupy
        git checkout ord-norm
        python3 -m pytest -v tests/cupy_tests/linalg_tests/test_norms.py
        
        
